### ISSUE TITLE
githubCsvTools immediately returns with no output

### ISSUE THREAD

**Issue by j-dimension** [gavinr/github-csv-tools#10]
githubCsvTools ./issues.csv

Just returns doing nothing, doesn't ask for OAuth token or any other information. Any idea what I might be missing?

**Comment by gavinr** [comment]
Are you sure the CSV is in a proper format?

**Comment by j-dimension** [comment]
I alsotried with the the CSVs contained as test files in the repo.

**Comment by gavinr** [comment]
What OS are you using? What Node.js and NPM versions are you using?

**Comment by j-dimension** [comment]
You've been pointing in the right direction. I have been using the versions of Node and npm that were contained in the package sources of my distro (probably outdated). I have downloaded manually and everything is fine now. Thanks!
