### ISSUE TITLE
Data leaking in the csv file

### ISSUE THREAD

**Issue by HaDoyle12** [gavinr/github-csv-tools#104]
### Discussed in https://github.com/gavinr/github-csv-tools/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **HaDoyle12** May  9, 2023</sup>

When pulling from a private repo, I am getting info from the issues in the rows of the csv file, this is causing issues cause we have to clean up the file before using. I also am not sure if all of the issues are being downloaded. This is a newer issue when running the tool. I am not even sure what could be causing the problem. </div>

**Comment by gavinr** [comment]
Hi, can you please clarify a bit more with an example and a replication case? Thank you.

**Comment by HaDoyle12** [comment]
Hi, yes I am using the tool to pull the issues from an internal repo, but the output looks like it contains data from the body of some of the issues. I have removed all sensitive data, but this is what my export files look like. Essentially there is data with breaks in the data set that looks like it is coming from the issues body. There isnt a pattern that I can see on how this data is getting into the file. *I also want to note this is a relatively new issue. My exports before March 23rd worked fine. 


![image](https://github.com/gavinr/github-csv-tools/assets/52761189/3e92f901-2da7-4299-8886-b7db34f2bacf)

**Comment by HaDoyle12** [comment]
Also while cleaning out the excess data there seems to be points at which there are issues missing. For instance issue 13522... 13520.. 13529 can be seen below.

**Comment by HaDoyle12** [comment]
![image](https://github.com/gavinr/github-csv-tools/assets/52761189/4409c73b-61d9-4c91-b4ce-de2f91a4c902)

**Comment by HaDoyle12** [comment]
![image](https://github.com/gavinr/github-csv-tools/assets/52761189/eaa44978-abbb-43fe-ac59-66de5571ab09)

**Comment by HaDoyle12** [comment]
The red boxes indicate the correct data, this shows that issue #13521 is missing from the data set and shows the spillover data from row 2194 to row 2240

**Comment by gavinr** [comment]
What program are you using to display the data? Most likely it's simply not handling multi-line csv cells gracefully. See related:

- https://github.com/gavinr/github-csv-tools/issues/17#issuecomment-621746674

**Comment by HaDoyle12** [comment]
I am using excel, I am working in Modern CSV and it is working perfectly! Thank you so much!
