### ISSUE TITLE
options `token, org, repo` for import

### ISSUE THREAD

**Issue by VladimirAlexiev** [gavinr/github-csv-tools#105]
Currently `githubCsvTools` asks for `token, org, repo` interactively.
It's a bit tedious to retype them several times until I get my CSV right.
Could you add command-line options?

**Comment by gavinr** [comment]
you can use these: https://github.com/gavinr/github-csv-tools#other-options

**Comment by VladimirAlexiev** [comment]
oh, sorry about this!
