### ISSUE TITLE
Is there support for threaded replies

### ISSUE THREAD

**Issue by tvogel8570** [gavinr/github-csv-tools#11]
I'm looking to bring over issues from a different system that has multiple replies to the original issue.  How is that handled using this application?

**Comment by gavinr** [comment]
Please see readme:

> Currently imports title, description, labels, and milestones.

Replies not currently supported (and I don't think GitHub would allow this because you cannot make a comment on someone else's behalf) - best workaround I would suggest would be to put the comments into the "description" in the original dataset then import.
