### ISSUE TITLE
Include first comment in CSV export

### ISSUE THREAD

**Issue by ad-si** [gavinr/github-csv-tools#14]
I understand that exporting the whole conversation thread of an issue is probably too complicated, but it would be cool if at least the first comment could be exported, as it mostly acts as the body of the issue. Would you be willing to include this?
Really helpful tool, btw. Thanks for building it!

**Comment by gavinr** [comment]
@ad-si You're welcome.

I do think additin the initial "first comment" to the default export would be useful.

Have you tried the `--exportComments` option?

**Comment by ad-si** [comment]
Oh damn, I checked out the `--help` page, but somehow I overlooked the `--exportComments` section 🙈. Quite useful, but the resulting format will be hard to import into other tools. So I guess an option to treat the first comment as the body would still be useful. My usecase is to import all GitHub issues into Redmine. So I just care about the issue and the body to get a gist of the issue. For details they can go back to the original GitHub issue. (Actually this would also be another useful field: The URL to the original GitHub issue)

**Comment by gavinr** [comment]
New in [v1.0.2](https://github.com/gavinr/github-csv-tools/releases/tag/v1.0.2): `body` is now included in the export, and you can now specify the output attribute columns using `--exportAttributes` - more info in the [updated readme](https://github.com/gavinr/github-csv-tools#to-export-issues).

**Comment by ad-si** [comment]
Awesome, thanks!
