### ISSUE TITLE
Exported body is only the first line of the original body

### ISSUE THREAD

**Issue by ad-si** [gavinr/github-csv-tools#17]

**Comment by gavinr** [comment]
seems like it's working for me - excel only shows the first line generally - do you see multiple lines if you open the CSV in a text editor?

**Comment by ad-si** [comment]
Haha damn, my fault, sorry! 🙈
I switched to https://www.moderncsv.com/, but the multiline support was a little surprising, so I didn't get there is more than one line available 😅.
