### ISSUE TITLE
Title required by GitHub, but not found in CSV.

### ISSUE THREAD

**Issue by Dinand-mmit** [gavinr/github-csv-tools#18]
Really stocked by import a csv file (from azure) with (backlog)issues.
After alle information as token, organisation and repo, it gives me 
Title required by GitHub, but not found in CSV.

But the first line in the csv is:
ID,Work Item Type,Title,Assigned To,State,Tags

I tested the csv online and in excel. Both work perfect, so the format is right. Even after conversion a rewritten file gives the same message. 

I attached a small version with 1 sample item (Upload refush csv, renamed to txt). It give the same message
[AzureIssues.txt](https://github.com/gavinr/github-csv-tools/files/4593246/AzureIssues.txt)

Can you help me to solve this, please.

**Comment by gavinr** [comment]
Please try setting `title` at the column name (all lower case). See the example CSV files here: https://github.com/gavinr/github-csv-tools/tree/master/test

**Comment by Dinand-mmit** [comment]
That wasn't very smart of me, sorry.
Yes it works perfect, thank you.

**Comment by benbowler** [comment]
If anyone comes to this later, I was getting this error when exporting the wrong CSV type from Excel, the MS-DOS csv works, the other types do now.
