### ISSUE TITLE
Support for importing from other online Git services? (e.g. GitLab)

### ISSUE THREAD

**Issue by Coteh** [gavinr/github-csv-tools#22]
Hi, just used this tool to move over some issues from an organization GitLab instance to my public GitHub. I was just wondering if there's any plans to support CSV formats from other providers such as GitLab or Bitbucket? For GitLab's CSV in particular, the header names are capitalized and I needed to lowercase "Title" to "title" to get it to work, then realized I forgot to lowercase other fields such as "Description" and those didn't get ported over.

Just thought I'd post this here and if it's out of scope of the project feel free to close. :)

**Comment by gavinr** [comment]
Thanks for the question. I've never really thought of it as supporting other "services" (like GitLab, etc), but just letting users know what the CSV columns should be and leaving it up to the user to set those properly.

I do think, based on your comment, that maybe we should warn the user if they're using a bad column name or something like that. That would've helped you in this case, correct? I haven't thought too much about it but would be open to ideas.

Additionally, we could have some wiki/help pages of "common services" and which columns you need to change.

**Comment by Coteh** [comment]
Yeah maybe some sort of way to map the columns within the CLI would help a lot. Could even have it as flags you can pass in to map the column (e.g. -c "Description:description") or have some sort of map config file that can be passed in (e.g. a JSON file that contains mappings of GitLab columns to their appropriate GitHub counterparts)

**Comment by Coteh** [comment]
I do understand though that this is meant to be a tool for importing/exporting GitHub Issue CSVs, so if providing an option to map column names to a GitHub column names is out of focus of that objective then we can think of something else that would be better suited for that focus.

**Comment by gavinr** [comment]
I would not be opposed to some sort of mapping option, if you'd want to PR that.

**Comment by typememo** [comment]
I submitted the pull request https://github.com/gavinr/github-csv-tools/pull/33.

@gavinr Could you review this?

**Comment by typememo** [comment]
Thank you for reviewing and accepting my pull request.
