### ISSUE TITLE
getting only the milestone Title

### ISSUE THREAD

**Issue by dev0zz** [gavinr/github-csv-tools#23]
Hi, I am trying to only get the milestone Title for the csv.

Do you have any idea, how to update the code, that instead of all the Milestone columns, I get something like this:

const defaultColumns = values.exportAttributes || [
        "created_at",
        "labels",
        **"milestone.title",**
        "number",
        "title",
        "body",
        "state",
      ];

thanks = ) 

great tool by the way^^

**Comment by gavinr** [comment]
Thanks! Could you be a bit more clear - maybe include a replication case? Thanks!

**Comment by gavinr** [comment]
Makes sense that you want to be able to choose some of the fields that have the dot in them. I think that could be a fix to allow that.

**Comment by gavinr** [comment]
This is now possible in v2.0.0:

```
githubCsvTools --exportAttributes number,title,milestone.title
```
