### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by nordine2017gitHub** [gavinr/github-csv-tools#29]
Hello,
When I'm trying to install the package using the following command : npm install -g github-csv-tools
I'm getting the error bellow 
npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! request to https://npm.pkg.gitub.com/<me>/github-csv-tools failed, reason: Hostname/IP does not match certificate's altnames: Host: npm.pkg.gitub.com. is not in the cert's altnames: DNS:*.mytrafficmanagement.com, DNS:mytrafficmanagement.com

can you help me please.
Best regards
NKH

**Comment by nordine2017gitHub** [comment]
The complete URL is https://npm.pkg.gitub.com/myGitHubUser/github-csv-tools

**Comment by nordine2017gitHub** [comment]
My node and npm version : 
$ node --version
v12.18.2

$ npm --version
6.14.5

Best regards
NKH

**Comment by gavinr** [comment]
Hi, it looks like you're trying to install from the GitHub package repository. This package is published on the NPM package repository: https://www.npmjs.com/package/github-csv-tools. Please refer to the documentation here: https://docs.npmjs.com/packages-and-modules/ If you have further problems with the NPM package repository, please refer to https://www.npmjs.com/support for help.
