### ISSUE TITLE
Add an option to format Issue number as link

### ISSUE THREAD

**Issue by mitchgrogg** [gavinr/github-csv-tools#32]
Would it be desirable to add an option to format the Issue number using the spreadsheet HYPERLINK function? For example, if enabled, convert the issue number to `=HYPERLINK("https://github.com/gavinr/github-csv-tools/issues/31", "31")` in the output CSV? That would enable an easy jump to the actual Issue page on GitHub. It appears that function is supported across various spreadsheet applications, including MS Excel, Apache OpenOffice, and Apple Numbers.

**Comment by gavinr** [comment]
Thanks for the idea! Right now the tool outputs CSV, which does not support excel-style functions. 

I think exporting to formats other than CSV are outside the scope of this tool, but I would encourage you to create and share a separate tool that might take the outputs of this tool and transform it into an excel file. If we work together we might make sure it's seamless using unix-style piping, for example:

```
githubCsvTools -e > githubCsvIssuesToExcel
```

(In this example, `githubCsvIssuesToExcel` would be your tool that takes the CSV and converts it to excel)


 If you do that, I'm happy to link to it in this repository's readme.

Thanks!
