### ISSUE TITLE
tool adds /repos/* to url?

### ISSUE THREAD

**Issue by andre-fxcm** [gavinr/github-csv-tools#34]
Hi, I have an enterprise url im trying to get issues from, but the tool adds /repos to my url, and it does not resolve in my enterprise github. how can i remove this added /repos ?

     url: 'https://github.internal/repos/Dev/foo/issues?state=all',

**Comment by gavinr** [comment]
Where are you seeing that? When you're exporting or importing?

**Comment by andre-fxcm** [comment]
I'm exporting from an internal enterprise github

-t repo -g https://github.internal -o Dev -r Foobar -e -v

**Comment by andre-fxcm** [comment]
error { HttpError: request to https://github.internal/repos/Dev/Foobar/issues?state=all failed, reason: unable to verify the first certificate
    at fetch.then.then.catch.error (D:\opt\node-v8.17.0-win-x64\node_modules\github-csv-tools\node_modules\@octokit\request\dist-node\index.js:107:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'HttpError',
  status: 500,
  headers: {},
  request:
   { method: 'GET',
     url: 'https://github.internal/repos/Dev/Foobar/issues?state=all',
     headers:
      { accept: 'application/vnd.github.v3+json',
        'user-agent': 'github-csv-tools octokit-rest.js/17.11.2 octokit-core.js/2.5.4 Node.js/8.17.0 (Windows 10; x64)',
        authorization: 'token [REDACTED]' },
     request: { hook: [Function: bound bound register] } } }

**Comment by andre-fxcm** [comment]
this path doesnt resolve in my enterprise install
https://github.internal/repos/Dev/Foobar/issues?state=all
I don't know why it has /repos/ added, this is correct url
https://github.internal/Dev/Foobar/issues?state=all

**Comment by andre-fxcm** [comment]
there might be some other problem with my ssh too, still trying to figure it out! thanks for your help :)

**Comment by gavinr** [comment]
> failed, reason: unable to verify the first certificate

Based on that, I think there might be an issue with your SSL certificate. Try this:
https://stackoverflow.com/questions/33820733/error-unable-to-verify-the-first-certificate-how-to-trust-all-certificates

**Comment by joeomc** [comment]
The -g needs to be passed the url to the api for on prem enterprise.
`-g https://github.internal/api/v3`

**Comment by JoshuaGarrison27** [comment]
The solution that @joeomc posted worked for me when I had this issue today. Hope this helps the next person that comes along with this problem.

**Comment by rmccaskill** [comment]
> The -g needs to be passed the url to the api for on prem enterprise. `-g https://github.internal/api/v3`

I ran into this tonight! Thank you for this response and for @JoshuaGarrison27 for confirming. It did indeed work for me! 
I submitted a pull request to make it more clear that the API path and the end isn't optional!

Thank you both!

**Comment by gavinr** [comment]
A reminder that `/api/v3` needs to be included in the enterprise url was added to the README doc in #52 and #64.
