### ISSUE TITLE
Add Sample CSV

### ISSUE THREAD

**Issue by Jared-Dev** [gavinr/github-csv-tools#35]
Would it be possible to add a sample CSV to the repository (or the `README`)?

**Comment by gavinr** [comment]
Do the sample CSVs in the test folder work for you? Or are you thinking something else?
https://github.com/gavinr/github-csv-tools/tree/master/test

**Comment by Jared-Dev** [comment]
Nope, those should be good! I just hadn't found them. Might be worth linking to or mentioning them in the README!

Thanks for the library!
