### ISSUE TITLE
After export with comments, import generates separate issues.

### ISSUE THREAD

**Issue by BadgerOnABike** [gavinr/github-csv-tools#48]
Recently I had to migrate everything over to a new organization and this tool helped massively. 

I found that, although the issue numbers were exported they were ignored (which I see now is in the code as title is the anchor) however it also generated a number of issues with the same title.

Is the behaviour intended to be able to import issues and comments or is it operating as expected?

(I did sort it out by manually moving the comments into a single issue line)

**Comment by gavinr** [comment]
Hi, 

>although the issue numbers were exported they were ignored 

when importing I do not think you can control the issue number - GitHub assigns issue numbers sequentially.

> however it also generated a number of issues with the same title

Could you please clarify that a bit more, and provide a replication case if you think it's a bug?

Thanks!
