### ISSUE TITLE
Importing milestones causes 'Validation Failed' error

### ISSUE THREAD

**Issue by RJDan** [gavinr/github-csv-tools#57]
I get the error (below) when trying to import my csv with a milestone column.
I have no errors when I remove the milestone column.
The milestone already exists in my repo. Trying to use another existing milestone or a new milestone produces the same error. 

RequestError [HttpError]: Validation Failed: {"value":"SprintJuly
1","resource":"Issue","field":"milestone","code":"invalid"}      
    at /usr/local/lib/node_modules/github-csv-tools/node_modules/
@octokit/request/dist-node/index.js:86:21                        
    at processTicksAndRejections (internal/process/task_queues.js
:97:5)                                                           
    at async Job.doExecute (/usr/local/lib/node_modules/github-cs
v-tools/node_modules/bottleneck/light.js:405:18) {

**Comment by ethanstrominger** [comment]
I get a different error: 
https://docs.github.com/rest/reference/issues#create-an-issue
I am using "V0.1.1" not a number.

**Comment by gavinr** [comment]
Duplicate of #27

**Comment by RJDan** [comment]
I got it to work by changing the the field title from "milestone" to "milestones".
"milestone" is the field that is exported from github so I thought to use that. On a whim I decided to try "milestones" and it worked without issue.

**Comment by lfoppiano** [comment]
I had a similar issue and I had to rename also "Description" to "Body"
