### ISSUE TITLE
Error: Error reading file

### ISSUE THREAD

**Issue by zoebosschaart** [gavinr/github-csv-tools#65]
Hi there,

our goal is to import a bulk of issues to our enterprise github organisation. However, each time that we try, we get the error in the screenshot. We have tried modifying the csv file with different seperators, and also different inputs for the organization. 
Could somebody help out to see what we do wrong here?
Thanks!

![image](https://user-images.githubusercontent.com/74196884/147231883-2371e89a-3905-4be4-a03b-b4550802a96c.png)

**Comment by gavinr** [comment]
Please try with one of the demo CSVs in the test folder: https://github.com/gavinr/github-csv-tools/tree/master/test

**Comment by zoebosschaart** [comment]
Thanks, that helped very much, we had some issues with the system settings of the delimiter. I'll close this issue!
