### ISSUE TITLE
Members of a GitHub Org can no longer import

### ISSUE THREAD

**Issue by joachimweyl** [gavinr/github-csv-tools#84]
Prior to the last update (#82) both members and Owners could import. Now only Owners of an Org can import to repos in that Org. After reviewing the last update it appears that [line 3](https://github.com/gavinr/github-csv-tools/blob/9919fc67755280b257cbda762ab2f035262d5c05/helpers.js#L3) of `helpers.js` might be the cause.

**Comment by joachimweyl** [comment]
I would say either state in the Readme that it only works for Owners/Admins. Or update the code so that it checks and switches based on your access level. The readme would then need something along the lines of letting users know that as an admin they should be able to import many issues and as a member they can only import 20 issues at a time.

**Comment by gavinr** [comment]
Note the discussion on trade-offs here: https://github.com/gavinr/github-csv-tools/discussions/83#discussioncomment-3423467
