### ISSUE TITLE
Fresh installation is not working for me

### ISSUE THREAD

**Issue by gaboesquivel** [gavinr/github-csv-tools#9]
```
➜  Downloads  node --version
v8.6.0
➜  Downloads  npm install -g github-csv-tools
/Users/user/.nvm/versions/node/v8.6.0/bin/githubCsvTools -> /Users/user/.nvm/versions/node/v8.6.0/lib/node_modules/github-csv-tools/index.js
+ github-csv-tools@0.2.0
updated 1 package in 0.611s
➜  Downloads  githubCsvTools --help          
env: node\r: No such file or directory
➜  Downloads  which githubCsvTools 
/Users/user/.nvm/versions/node/v8.6.0/bin/githubCsvTools
```

**Comment by gaboesquivel** [comment]
I had to do this

```
brew install tofrodos
fromdos /Users/gabo/.nvm/versions/node/v8.6.0/lib/node_modules/github-csv-tools/index.js
```

**Comment by gavinr** [comment]
@gaboesquivel thank you for the issue report. It seems like you're on Mac OS - what version are you on? Do you know what aspect of the code makes the `tofrodos` package required? Maybe a line-endings problem? I'm happy to modify to make the package more widely useful if we can identify the problem.

Thanks again!

**Comment by gaboesquivel** [comment]
Yeah, it is the line endings problem

**Comment by gavinr** [comment]
@gaboesquivel  I have re-published v0.3.0 with unix-style line breaks instead of windows - can you please remove/reinstall and let me know if that helps?

**Comment by gaboesquivel** [comment]
Hi @gavinr, I really don't have time for this right now.  I ended up creating this script https://github.com/gaboesquivel/pivotal-to-zenhub  back then

**Comment by gavinr** [comment]
nice! love it. I'll close this for now then. Thanks for the original issue report.
