### ISSUE TITLE
Can I pull issues down from a private repo? 

### ISSUE THREAD

**Issue by ajsaule** [gavinr/github-csv-tools#95]
I am doing the following:

<img width="424" alt="Screenshot 2022-12-14 at 11 08 27 am" src="https://user-images.githubusercontent.com/49604000/207472269-4f13899a-8a4f-4080-9f8f-493128a3eee7.png">

I keep getting `Error reading file.`, I assume maybe because it's a private repo? But my account definitely has access to the repo. 

Is there any quick way around this issue at the moment?

**Comment by gavinr** [comment]
Please ask support questions in the "Discussions" tab.
