### ISSUE TITLE
Milestone is detected as string and import fails

### ISSUE THREAD

**Issue by vhartikainen** [gavinr/github-csv-tools#98]
Version: 3.1.4
Node version: v18.12.1

Trying to import the following data:
```
title,body,state,milestone,labels
"1.1.1 Welcome Screen (UI)","Body of issue",open,1,"1.1 Registration,UI"
````

Will result in HTTP 422 and RequestError [HttpError]: Invalid request.
For 'properties/milestone', "1" is not an integer or null.

**Comment by gavinr** [comment]
Milestone is not currently supported, see https://github.com/gavinr/github-csv-tools/issues/27

**Comment by gavinr** [comment]
Oops - sorry, milestone is supported, but this needs to be fixed. See #90
