### ISSUE TITLE
As a member, I can not import to internal Org repos

### ISSUE THREAD

**Issue by kleinerwilliam** [gavinr/github-csv-tools#99]
Hi, when I use the api to import data to a repo from an internal organization, I get this error:

<img width="1512" alt="Screenshot 2023-02-17 at 09 04 55" src="https://user-images.githubusercontent.com/42767238/220049505-fd6ee416-34db-4dc4-a136-23e9555ed365.png">
 
Even though I authorize the organization:
<img width="841" alt="Screenshot 2023-02-17 at 08 58 00" src="https://user-images.githubusercontent.com/42767238/220049580-7c93ee21-7dfc-4525-b0d5-8fa06d6cb166.png">

Does someone have any ideas? Thanks in advance

**Comment by gavinr** [comment]
Seems like probably wrong org name. Please open support questions in the Discussions area.
